config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"   #root za usera koji je logovan
  end
  
  root 'welcome#index'                            #root za usera koji nije logovan
  
  
end

app/models/doc.rb
class Doc < ActiveRecord::Base
    belongs_to :user #All documents belong to user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]


    def index
        @docs = Doc.where(user_id: current_user)     #Doc.all.order("created_at DESC") izbrisano nakon User modula. Svaki User moze vidjeti samo svoje docs.
    end
  
    def show
    end
    
    def new
        @doc = current_user.docs.build        # @doc = Doc.new -ovo smo promjenili kada smo dodali User model!
    end
    
    def create
        @doc = current_user.docs.build(doc_params)   #@doc = Doc.new(doc_params) isto tako i ovde smo promjenili
        if @doc.save
            redirect_to @doc
        else
            render_to 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @doc.update(doc_params)
            redirect_to @doc
        else
            render 'edit'
        end
    end
    
    def destroy
        @doc.destroy
        redirect_to docs_path
    end
    
    private
    
      def find_doc
          @doc = Doc.find(params[:id])
      end
      
      def doc_params
          params.require(:doc).permit(:title, :content)
      end
  


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :content
    = f.button :submit, class: "button"
    

app/views/docs/edit.html.haml
.wrapper_with_padding

    %h1 Fix Doc!
    
    =render 'form'
    
    =link_to "Cancel", doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)      
            %p.content= truncate(doc.content, length:50)
  

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc!
    
  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
    %h1= @doc.title
    %p= @doc.content
    
    = link_to "All Docs", docs_path
    = link_to "Fix Doc", edit_doc_path(@doc)
    = link_to "Trash It", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }



 

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileCabinet | Your Life's work!
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to "FileCabinet", root_path, id: "logo"
      
      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        
        - else
          = link_to "Log In", new_user_session_path
          
  %p.notice= notice
  %p.alert= alert
  
  
  = yield  

app/views/welcome/index.html.haml
#banner
    .banner_content
        %h1 File Cabinet
        %p Your life's work. Organized, always.
        %button= link_to "Enter", new_user_registration_path
        
#callouts
    .callout_inner
        .wrapper
            .callout
                %h2 Organized
                %p Microdosing cornhole vegan kickstarter heirloom ugh bitters ennui paleo put a bird on it wolf next level offal XOXO pickled. Quinoa franzen actually chambray sriracha. Twee try-hard iceland, before they sold out photo booth ethical bitters. Gluten-free portland chillwave, skateboard flexitarian 8-bit affogato raw denim typewriter helvetica venmo meggings franzen. Small batch occupy yr flannel bitters, vape shoreditch. Salvia vaporware sriracha photo booth, gochujang twee occupy taxidermy asymmetrical etsy. Hammock succulents kinfolk, listicle 90's PBR&B keytar lumbersexual gentrify mixtape wayfarers af.

#bottom_cta
    .wrapper
        %h2 Go Ahead!
        %br
        %button= link_to "Join Now", new_user_registration_path